# Generated by Django 2.2.6 on 2019-10-21 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FireReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inci_no', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('alm_date', models.DateField()),
                ('alm_time', models.TimeField()),
                ('building_num', models.CharField(max_length=100)),
                ('street_num', models.CharField(max_length=100)),
                ('lattitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('incident_type', models.CharField(max_length=100)),
            ],
        ),
    ]
